[pytest]

addopts = -p no:playwright
          -p no:base_url
          --headed
          --tracing=retain-on-failure
          --screenshot=only-on-failure
          --video=retain-on-failure
          --env=pre

log_cli = true
log_cli_level = debug

# 测试用例路径
testpaths = cases

# 测试文件匹配模式
python_files = test_*.py
python_classes = Test*
python_functions = test_*
